In [3]:
pip install scikit-image

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.2.1 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [4]:
pip install -U scikit-learn


[notice] A new release of pip is available: 23.2.1 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip



  Obtaining dependency information for scikit-learn from https://files.pythonhosted.org/packages/7b/0e/25d6b5678ed3c7e12bc94d047d0e9492e89cc78b7ea0034ac0f1cf2ff304/scikit_learn-1.4.1.post1-cp311-cp311-win_amd64.whl.metadata
  Obtaining dependency information for joblib>=1.2.0 from https://files.pythonhosted.org/packages/10/40/d551139c85db202f1f384ba8bcf96aca2f329440a844f924c8a0040b6d02/joblib-1.3.2-py3-none-any.whl.metadata
  Obtaining dependency information for threadpoolctl>=2.0.0 from https://files.pythonhosted.org/packages/1e/84/ccd9b08653022b7785b6e3ee070ffb2825841e0dc119be22f0840b2b35cb/threadpoolctl-3.4.0-py3-none-any.whl.metadata
   ---------------------------------------- 0.0/10.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/10.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/10.6 MB 660.6 kB/s eta 0:00:17
   ---------------------------------------- 0.0/10.6 MB 393.8 kB/s eta 0:00:27
   ---------------------------------------- 0.1/10.6 MB

In [11]:
import os
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
from skimage import io, transform
import numpy as np

# Ganti dengan direktori yang berisi folder dataset
dataset_dir = 'C:\Bunga\Dataset'

# Inisialisasi daftar kelas dan label
classes = ['Tulip', 'Mawar', 'Bunga Matahari']
labels = [0, 1, 2]

X_train = []
y_train = []

# Load data training
for label, class_name in zip(labels, classes):
    class_dir = os.path.join(dataset_dir, class_name)
    
    # Untuk setiap gambar dalam kelas
    for image_name in os.listdir(class_dir):
        image_path = os.path.join(class_dir, image_name)
        
        # Ubah gambar menjadi ukuran yang sama
        image = io.imread(image_path, as_gray=True)
        image = transform.resize(image, (100, 100))  # Ubah ukuran gambar menjadi 100x100
        
        # Ubah gambar menjadi larik nilai piksel
        image_flattened = image.flatten()
        
        # Tambahkan gambar dan label kelas ke data training
        X_train.append(image_flattened)
        y_train.append(label)

X_train = np.array(X_train)
y_train = np.array(y_train)

print("Data Training (X_train):")
print(X_train)
print("Label Training (y_train):")
print(y_train)

# Inisialisasi model SVM
svm = SVC()

# Latih model SVM menggunakan data training
svm.fit(X_train, y_train)

# Inisialisasi model KNN
knn = KNeighborsClassifier()

# Latih model KNN menggunakan data training
knn.fit(X_train, y_train)

# Load data testing
X_test = []
y_test = []
test_dir = 'C:\Bunga\Train'

# Untuk setiap gambar dalam folder testing
for image_name in os.listdir(test_dir):
    image_path = os.path.join(test_dir, image_name)
    
    # Ubah gambar menjadi ukuran yang sama
    image = io.imread(image_path, as_gray=True)
    image = transform.resize(image, (100, 100))  # Ubah ukuran gambar menjadi 100x100
    
    # Ubah gambar menjadi larik nilai piksel
    image_flattened = image.flatten()
    
    # Tambahkan gambar dan label kelas ke data testing
    X_test.append(image_flattened)
    # Tambahkan label dummy karena tidak diketahui
    y_test.append(-1)

X_test = np.array(X_test)
y_test = np.array(y_test)

# Prediksi kelas dari data testing menggunakan model SVM
y_pred_svm = svm.predict(X_test)

# Cetak hasil prediksi menggunakan model SVM
print("Hasil Prediksi (SVM):")
for i, pred in enumerate(y_pred_svm):
    class_name = classes[pred]
    print("Gambar", i+1, ": Prediksi =", class_name)

# Prediksi kelas dari data testing menggunakan model KNN
y_pred_knn = knn.predict(X_test)

# Cetak hasil prediksi menggunakan model KNN
print("Hasil Prediksi (KNN):")
for i, pred in enumerate(y_pred_knn):
    class_name = classes[pred]
    print("Gambar", i+1, ": Prediksi= ", class_name)

# Evaluasi akurasi model SVM
y_train_pred_svm = svm.predict(X_train)
train_accuracy_svm = accuracy_score(y_train, y_train_pred_svm)
print("Akurasi Model SVM (Data Training):", train_accuracy_svm)

# Evaluasi akurasi model KNN
y_train_pred_knn = knn.predict(X_train)
train_accuracy_knn = accuracy_score(y_train, y_train_pred_knn)
print("Akurasi Model KNN (Data Training):", train_accuracy_knn)

Data Training (X_train):
[[0.58588436 0.58849433 0.58678007 ... 0.76441447 0.78343762 0.84191386]
 [0.97254902 0.97254902 0.97254902 ... 0.94117603 0.94102699 0.94055895]
 [0.99999987 0.99991419 0.99948648 ... 1.         1.         1.        ]
 ...
 [1.         1.         1.         ... 0.43311184 0.28422068 0.40236233]
 [0.18197183 0.17848851 0.20051143 ... 0.62695129 0.60976588 0.602478  ]
 [0.34496677 0.36652312 0.40641751 ... 0.38865441 0.38468254 0.38110308]]
Label Training (y_train):
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
Hasil Prediksi (SVM):
Gambar 1 : Prediksi = Tulip
Gambar 2 : Prediksi = Bunga Matahari
Gambar 3 : Prediksi = Mawar
Hasil Prediksi (KNN):
Gambar 1 : Prediksi=  Tulip
Gambar 2 : Prediksi=  Tulip
Gambar